-- ANTENNE TABLE: ANTENNE
--DROP TABLE IF  EXISTS antenne;
CREATE TABLE IF NOT EXISTS antenne (
	ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	MAC VARCHAR(255) DEFAULT NULL,
	PRIMARY KEY(ID)
	);
	
	CREATE TABLE IF NOT EXISTS position (
	ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) DEFAULT NULL,
	X DOUBLE DEFAULT NULL,
	Y DOUBLE DEFAULT NULL,
	PRIMARY KEY(ID)
	);
	
	CREATE TABLE IF NOT EXISTS piste (
	ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) DEFAULT NULL,
	PRIMARY KEY(ID)
	);
	
CREATE TABLE IF NOT EXISTS mesure (
	ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	Antenne_ID BIGINT(20) NOT NULL,
	Position_ID BIGINT(20) NOT NULL,
	Piste_ID BIGINT(20) NOT NULL,
	PRIMARY KEY(ID)
	);
	